import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Simplified translation helper for common UI elements
const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.home': '首页',
    'nav.visa': '签证',
    'nav.discover': '发现',
    'nav.tools': '工具',
    'nav.catalog': '目录',
    'nav.slogan': '旅行中国出发',
    'nav.lang': '简体中文',
    'nav.lang.code': 'CN',
    'visa.mega.title': '来华免签大全',
    'visa.mega.desc': '无需签证，畅游中国！全面了解中国240小时过境免签政策和国家，中国单方面免签国家，中外互免签证国家，开启您的精彩中国之旅！',
    'visa.mega.view': '立即查看',
    'visa.types': '签证类型',
    'visa.photo': '照片要求',
    'visa.fee': '费用标准',
    'visa.form': '填写申请表',
    'visa.card': '入境卡填写指南',
    'discover.hotCities': '热门城市',
    'discover.moreCities': '更多城市',
    'discover.guides': '经验攻略',
    'discover.guides.desc': '资深达人分享实用攻略，助你轻松玩转中国',
    'discover.pocket': '中国旅行锦囊',
    'discover.pocket.desc': '5分钟掌握入华锦囊，针对来华新手打造，第一次去中国必看',
    'tools.menu': '中文菜单转图神器',
    'tools.menu.desc': '上传照片，可获得图片、翻译、食材和价格，助您轻松点餐',
    'tools.name': '中文名取名大师',
    'tools.name.desc': '使用AI推理模型中文名，适合在中国职业发展、交友、旅游或生活',
    'tools.pinyin': '中文转拼音和分词',
    'tools.pinyin.desc': '可将任何中文句子转换为标准拼音、智能分词，查看每个字的笔顺动画',
    'tools.counter': '中文字符计数器',
    'tools.counter.desc': '精确统计汉字、英文、数字、标点、行数与总字符数',
    'tools.zodiac': '中国生肖计算器',
    'tools.zodiac.desc': '根据生日计算中国生肖，查看本命年时间，并了解每个生肖的文化含义。',
    'footer.about': '关于我们',
    'footer.contact': '联系我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.desc': 'TripCNGo 为您的中国之旅提供全面指南和实用工具。',
    'hero.title': '发现真实的中国',
    'hero.subtitle': '从签证指南到旅行锦囊，我们为您提供一站式入华服务',
    'hero.ultimate': '您中国旅行的终极指南',
    'hero.desc': '提供免签政策、中国文化、AI智能工具，助您轻松探索中国',
    'hero.dest': '目的地',
    'hero.aiName': 'AI中英文取名大师',
    'hero.searchPlaceholder': '请输入您想去的城市',
    'hero.start': '开始',
    'visa.section.title': '关于240小时过境免签政策',
    'visa.section.desc': '中国扩大了对多个国家的144小时及最新推出的240小时过境免签政策。符合条件的外国旅游者、商务人士可以通过指定口岸入境，无需事先申请签证即可在中国指定区域内停留最长不超过6天至10天。',
    'visa.stat.countries': '54国',
    'visa.stat.countries.desc': '开放国家',
    'visa.stat.stay': '240h',
    'visa.stat.stay.desc': '停留时长',
    'visa.stat.provinces': '24个',
    'visa.stat.provinces.desc': '开放省份',
    'visa.stat.ports': '60+',
    'visa.stat.ports.desc': '入境口岸',
    'home.cities.title': '热门中国城市',
    'home.cities.more': '更多城市',
    'home.guides.title': '漫游指南',
    'home.guides.more': '更多攻略',
    'home.guides.helpful': '人认为有用',
    'home.faq.title': '常见问题',
    'home.faq.subtitle': '关于144/240小时过境免签政策问答',
    'guide.cat.all': '全部',
    'guide.cat.policy': '国家政策',
    'guide.cat.payment': '支付方式',
    'guide.cat.transport': '交通出行',
    'guide.cat.tools': '实用工具',
    'guide.cat.city': '城市指南',
    'guide.cat.tradition': '传统文化',
    'guide.cat.food': '美食文化',
    'footer.brand.title': 'tripcngo.com',
    'footer.brand.desc': 'tripcngo.com，是一个专注于减少中国旅游信息差，提升入境自由行旅游体验的旅游品牌，致力于向世界传播中国文化，发现真实美好的中国；',
    'footer.links.visa': '入境签证',
    'footer.links.visa.all': '来华免签大全',
    'footer.links.visa.dest': '发现目的地',
    'footer.links.visa.nav': '导航信息',
    'footer.links.company': '公司',
    'footer.links.about': '关于我们',
    'footer.links.terms': '服务条款',
    'footer.links.privacy': '隐私政策',
    'footer.links.feedback': '意见反馈',
    'feedback.title': '联系我们',
    'feedback.subtitle': '提出您对漫游中国的建议或您希望解决的问题，我们会尽快给您答复',
    'feedback.name': '姓名',
    'feedback.name.placeholder': '请输入您的姓名',
    'feedback.email': '邮箱',
    'feedback.email.placeholder': '请输入您的邮箱',
    'feedback.message': '留言',
    'feedback.message.placeholder': '您可以告诉我们您来中国面临的最大问题是什么？或者给我们提供建议，我们将真诚给您反馈和帮助',
    'feedback.submit': '提交',
    'feedback.success': '提交成功！我们将尽快给您答复。',
    'feedback.error': '提交失败，请稍后再试。',
    'footer.links.lang': '语言',
    'footer.copy': '© 2026 tripcngo.com. 版权所有。',
    'about.hero.title': '为什么选择我们？',
    'about.features.team.title': '本土专业团队',
    'about.features.team.desc': '我们是一群热爱旅行的本土团队，了解最新政策，掌握小众玩法，能为您提供专业信息和服务',
    'about.features.focus.title': '专注自由行',
    'about.features.focus.desc': '我们只为自由行爱好者服务，提供个性化、定制化的行程方案，让您的旅程更加精彩',
    'about.features.ai.title': '智能AI助力',
    'about.features.ai.desc': '我们的智能AI助手能够读懂您的需求，快速生成定制行程，专业的指南内容，让规划和旅途都轻松无忧',
    'about.story.title': '我们的故事',
    'about.story.p1': 'tripcngo.com的诞生，源于我们对中国的热爱和对自由行体验的执着。',
    'about.story.p2': '我们坚信旅行是随性且充满惊喜的，而非程式化的拍照打卡，它应该是一种随心而动、随遇而安的体验。',
    'about.story.p3': '随着中国240小时过境免签政策的推行，越来越多的外国朋友踏上这片古老而神秘的土地，我们真心希望每位旅行者都能享受充满乐趣和惊喜的旅程。然而，现实中存在不少挑战：语言不通、网络不畅、线下支付不便、信息零散以及规划难等，都可能让人望而却步。我们要感受中国的美好，一个全面、实用的指南必不可少。',
    'about.story.p4': '因此，我们创立了tripcngo.com，我们从介绍中国文化、弥合信息鸿沟入手，结合团队的旅行经验、对中国文化的理解以及对AI技术的执着，共同打造了这个平台。',
    'about.story.p5': '从签证指导到旅行攻略，从文化探索到智能助手，我们希望能帮助每位旅行者轻松规划行程，深入体验，从而发现一个真实而美好的中国。',
    'about.team.title': '我们的团队',
    'about.team.subtitle': 'tripcngo.com 是由这些出色的个人创建',
    'privacy.hero.title': '隐私政策',
    'privacy.hero.subtitle': '我们致力于保护您的个人信息和隐私安全',
    'privacy.lastUpdated': '最后更新日期：2025年4月26日',
    'terms.hero.title': '服务条款',
    'terms.hero.subtitle': '使用本网站即表示您同意条款',
    'zodiac.title': '中国生肖计算器',
    'zodiac.subtitle': '根据生日查询你的中国生肖，了解生肖文化，并查看本命年时间与旅行灵感。',
    'tools.hero.title': '旅行助手',
    'tools.hero.subtitle': '让您的中国之旅更加便捷的小工具',
    'tools.char.title': '中文字符计数器',
    'tools.char.desc': '粘贴文本，为您快速统计字符组成。',
    'tools.char.total': '总字符',
    'tools.char.zh': '中文',
    'tools.char.en': '英文',
    'tools.char.digits': '数字',
    'tools.char.punc': '标点',
    'tools.char.placeholder': '粘贴或输入文本以开始统计...',
    'tools.zodiac.search': '查阅您的生肖',
    'tools.menu.hero.title': '将中文菜单转换成图片',
    'tools.menu.hero.desc': '一键扫描菜单，利用 DeepSeek V4 级精准分析，获取双语翻译、真实对比图与价格换算。',
    'tools.menu.upload.title': '上传菜单图片',
    'tools.menu.upload.subtitle': '精准解析菜品 & 极速翻译',
    'tools.menu.upload.button': '选择图片',
    'tools.menu.status.reset': '放弃并重试',
    'tools.menu.status.analyzing': 'DeepSeek 正在深度解析中...',
    'tools.menu.label.raw': '原始识别区域',
    'tools.menu.label.refined': 'DeepSeek 深度优化结果',
    'tools.menu.placeholder': '请先上传菜单',
    'tools.menu.feature.1.title': '深度识别',
    'tools.menu.feature.1.desc': '专为手写与艺术字体优化的 AI 模型。',
    'tools.menu.feature.2.title': '视觉生成',
    'tools.menu.feature.2.desc': '让您在点餐前就能亲眼“看见”美食。',
    'tools.menu.feature.3.title': '汇率换算',
    'tools.menu.feature.3.desc': '实时外币换算，预算尽在掌控。',
    'tools.menu.feature.4.title': '语音辅助',
    'tools.menu.feature.4.desc': '点餐时一键播放标准中文发音。',
    'tools.zodiac.year': '出生年份',
    'tools.zodiac.month': '出生月份',
    'tools.zodiac.day': '出生日期',
    'tools.zodiac.button': '查询我的生肖',
    'tools.zodiac.monthUnit': '月',
    'tools.zodiac.dayUnit': '日',
    'tools.zodiac.result': '查询结果：{year}年出生，您的生肖是：',
    'tools.zodiac.faq1.title': '生肖年从什么时候开始变化？',
    'tools.zodiac.faq1.desc': '生肖并不是从1月1日开始，而是从每年的春节（农历正月初一）开始变化。',
    'tools.zodiac.faq2.title': '十二生肖详解',
    'tools.zodiac.faq2.desc': '中国文化中共有十二种生肖，它们分别是：鼠、牛、虎、兔、龙、蛇、马、羊、猴、鸡、狗、猪。',
    'tools.name.title': '中文姓名生成器',
    'tools.pinyin.title': '拼音分词工具',
    'guide.hero.title': '中国旅行指南',
    'guide.hero.subtitle': '5分钟掌握入华锦囊，第一次去中国必看',
    'guide.hero.desc': '本专题专为第一次去中国的外国朋友打造，旨在解决您在华期间最紧迫、最常见的“痛点”，让您能够快速了解中国，并开启一段愉快的中国之旅。',
    'guide.toolbox.title': '数字生存工具包',
    'guide.toolbox.desc': '网络连接与移动支付的必备指南',
    'guide.toolbox.vpn.important': '重要提醒',
    'guide.toolbox.vpn.note': '必须在入华前下载并安装VPN！在中国境内无法下载。',
    'guide.toolbox.vpn.why': '为什么需要VPN？',
    'guide.toolbox.net': '手机网络选择',
    'guide.toolbox.payment.status': '中国已进入准无现金社会',
    'guide.toolbox.payment.manual': '支付操作手册',
    'guide.toolbox.payment.setup': '设置步骤',
    'guide.toolbox.payment.alipay': '首选：支付宝 (Alipay)',
    'guide.toolbox.lang.title': '语言工具箱',
    'guide.toolbox.lang.desc': '高频词汇常用对话，轻松应对日常沟通',
    'guide.toolbox.lang.core': '高频核心词汇',
    'guide.toolbox.lang.phrases': '情景对话手册',
    'guide.toolbox.chars.title': '核心汉字快速识别',
    'guide.toolbox.culture.title': '文化指南针',
    'guide.toolbox.discover': '发现更多',
    'cities.hero.title': '中国热门城市',
    'cities.hero.desc': '探索中国最受欢迎的城市。了解北京、上海、广州有什么好玩的，发现顶级餐饮和购物推荐，甚至一些趣味知识，轻松规划您的行程。',
    'cities.intro.title': '中国简介',
    'cities.intro.p1': '中华人民共和国，是世界上历史最悠久的国家之一，拥有5000年的文明历史。',
    'cities.intro.p2': '中国位于亚洲东部，太平洋西岸，1949年建国，是一个人民民主专政的社会主义制度国家，也是世界上人口最多的国家之一，拥有14亿人口，国土面积约960万平方公里，是世界上面积第三大的国家。',
    'cities.intro.p3': '中国的地势呈西高东低的三级阶梯，以高耸的青藏高原为起点，向东逐级下降至平原和海岸线。这种巨大的落差造就了从世界屋脊到东部沿海的丰富地貌，拥有包括沙漠、高原、盆地和平原等多样景观，并孕育了长江、黄河两大水系。',
    'cities.intro.p4': '中国分为23个省、5个自治区、4个直辖市（北京、上海、天津、重庆）和2个特别行政区（香港、澳门）。首都北京是全国的政治和文化中心，而上海则是重要的经济和金融枢纽。',
    'cities.intro.p5': '中国疆域辽阔、民族众多，共有56个官方认定的民族，以汉族为主体，通用汉语、汉字，汉族与少数民族统称为“中华民族”，自称“炎黄子孙”、“龙的传人”。',
    'cities.intro.p6': '中国文化渊远流长、博大精深、绚烂多彩，是东亚文化圈的文化宗主国，在世界文化体系内占有重要地位，由于各地的地理位置、自然条件的差异，人文、经济方面也各有特点。传统文化艺术形式有诗词、戏曲、书法、国画等，而春节、元宵、清明、端午、中秋、重阳等则是中国重要的传统节日。',
    'city.beijing': '北京',
    'city.shanghai': '上海',
    'city.guangzhou': '广州',
    'city.shenzhen': '深圳',
    'city.hangzhou': '杭州',
    'city.chongqing': '重庆',
    'city.chengdu': '成都',
    'city.xian': '西安',
    'city.changsha': '长沙',
    'city.xiamen': '厦门',
    'footer.links.partners': '合作伙伴',
    'city.tags.visaFree': '240小时过境免签',
    'city.stats.wantToVisit': '想去',
    'city.stats.recommended': '推荐',
    'city.weather.timeTitle': '时间',
    'city.weather.area': '面积',
    'city.weather.population': '常住人口',
    'city.bestTime.title': '最佳旅行时间',
    'city.bestTime.descPrefix': '游览',
    'city.bestTime.descSuffix': '的最佳时间是',
    'city.history.title': '历史与文化',
    'city.attractions.title': '景点',
    'city.attractions.subtitle': '有哪些好玩的推荐',
    'city.attractions.ticket': '门票',
    'city.attractions.season': '适宜季节',
    'city.attractions.time': '建议游玩',
    'city.heritage.world.title': '世界遗产名录',
    'city.heritage.world.subtitle': '拥有的联合国教科文组织世界遗产',
    'city.heritage.intangible.title': '非物质文化遗产',
    'city.heritage.intangible.subtitle': '探索丰富的非物质文化遗产，了解传统工艺与文化精髓',
    'city.transport.title': '交通指南',
    'city.transport.subtitle': '你必须知道的交通工具',
    'city.food.title': '美食',
    'city.food.subtitle': '品尝最地道、最受欢迎的特色美食与小吃',
    'city.food.ingredients': '主要食材',
    'city.explore.title': '深入探索',
    'city.explore.travel': '旅行',
    'city.explore.hotels': '酒店与住宿',
    'city.explore.tools': '网络如何用与在线工具',
    'visa.hero.legendTitle': '240小时过境免签开放城市',
    'visa.hero.legendFull': '全省/市开放',
    'visa.hero.legendPartial': '部分地区开放',
    'visa.menu.types': '签证类型',
    'visa.menu.photo': '照片要求',
    'visa.menu.fee': '费用标准',
    'visa.menu.form': '填写申请表',
    'visa.menu.entryCard': '入境卡填写指南',
    'visa.menu.download': '材料下载',
    'visa.transit.title': '来华240小时过境免签',
    'visa.transit.countriesTitle': '开放国家 (54个)：',
    'visa.transit.europe': '欧洲 (44个国家)：',
    'visa.transit.americas': '美洲 (6个国家)：',
    'visa.transit.oceania': '大洋洲 (2个国家)：',
    'visa.transit.asia': '亚洲 (6个国家)：',
    'visa.transit.portsTitle': '适用口岸：',
    'visa.transit.tableCity': '城市',
    'visa.transit.tablePort': '入境口岸名称',
    'visa.transit.tableArea': '停留活动范围',
    'visa.unilateral.title': '单方面免签国家一览表',
    'visa.unilateral.desc': '中国向以下国家持普通护照公民来华旅游、经商、探亲等开放免签，入境无需提前申请签证',
    'visa.unilateral.tableCountry': '国家名称',
    'visa.unilateral.tableDays': '停留天数',
    'visa.mutual.title': '互免签证协定国家一览表',
    'visa.mutual.desc': '双方国家公民持因私普通护照来往，彼此国家短期旅行通常无需事先申请签证',
    'visa.mutual.tableCountry': '国家名称',
    'visa.mutual.tableDays': '停留天数',
    'visa.faq.title': '常见问题',
    'visa.sidebar.notice': '注意事项',
    'visa.sidebar.portTitle': '选口岸：60个指定入境点',
    'visa.sidebar.portDesc1': '适用人群：54国公民（如美、英、日等）',
    'visa.sidebar.portDesc2': '入境要求：仅限北京、上海、广州等60个指定口岸，其他口岸不可用。',
    'visa.sidebar.materialTitle': '备材料：联程机票+有效护照',
    'visa.sidebar.materialDesc1': '必备文件：护照有效期 > 3个月',
    'visa.sidebar.materialDesc2': '已订妥的联程机票（入境后240小时内飞往第三国，不可返回出发国）',
    'visa.sidebar.materialDesc3': '申请流程：入境时向口岸边检提交材料，审核通过后放行。',
    'visa.sidebar.areaTitle': '守区域：24省活动范围',
    'visa.sidebar.areaDesc1': '允许范围：可在北京、上海、四川等24个省（区、市）内旅游或跨省活动。',
    'visa.sidebar.areaDesc2': '禁止行为：超出规定区域停留。',
    'visa.sidebar.ruleTitle': '遵法规：时限与登记严遵守',
    'visa.sidebar.ruleDesc1': '时限要求：最长停留240小时（从入境次日0时起算）',
    'visa.sidebar.ruleDesc2': '超时/超范围：须提前向公安机关申请停留证件（仅限紧急或不可抗力）。',
    'visa.sidebar.ruleDesc3': '登记义务：入境24小时内办理住宿登记（酒店或派出所）。',
    'visa.sidebar.ruleDesc4': '仅限旅游、商务等短期活动，禁止工作或学习。',
    'visa.sidebar.disclaimer': '免责声明：本网站提供的信息仅供参考，具体政策请以中国国家移民管理局官方发布为准。政策可能随时调整，请在出行前确认最新规定。',
    'visa.sidebar.niaTitle': '中国移民管理局',
    'visa.sidebar.hotline': '服务热线',
    'visa.sidebar.interaction': '互动交流',
    'visa.nav.title': '— 签证业务 —',
    'visa.nav.types': '签证类型',
    'visa.nav.photo': '照片要求',
    'visa.nav.fee': '费用标准',
    'visa.nav.form': '填写申请表',
    'visa.nav.arrival': '入境卡填写指南',
    'visa.nav.downloads': '材料下载',
    'visa.hero.title': '签证业务',
    'visa.hero.desc': '全面了解中国签证信息，轻松办理签证，开启中国之旅',
    'visa.breadcrumb.home': '首页',
    'visa.breadcrumb.mega': '来华免签大全',
    'guide.noArticles': '暂无相关内容，正在努力更新中...',
    'guide.prev': '上一页',
    'guide.next': '下一页',
    'guide.recommend': '推荐指南',
    'guide.recommendCity': '推荐城市',
    'guide.views': '人浏览',
    'guide.helpful': '人认为有用',
    'guide.updated': '最后更新日期',
    'guide.author': '作者',
    'guide.inCategory': '在 ',
    'guide.readMore': '阅读全文',
    'guide.backToList': '返回列表',
    'guide.articleNotFound': '文章不存在',
    'guide.prevPost': '上一篇',
    'guide.nextPost': '下一篇',
    'tools.name.inputLabel': '英文名或含义',
    'tools.name.placeholder': "例如: Jonathan, 或 '希望勇敢'",
    'tools.name.gender': '性别',
    'tools.name.male': '男',
    'tools.name.female': '女',
    'tools.name.button': '生成中文名',
    'tools.name.generating': '正在生成...',
    'tools.pinyin.inputPlaceholder': '输入中文句子以开始分析...',
    'tools.pinyin.button': '分析',
    'tools.pinyin.result': '分析结果:',
    'apps.hero.title': '中国之旅必备应用 2026',
    'apps.hero.subtitle': '（最新版）',
    'apps.hero.desc': 'Google、Uber 在中国无法使用？无需担心。本指南为您收录 2026 年最受当地人喜爱的必备 App，涵盖移动支付、交通、社交、外卖，让您像本地人一样轻松畅游中国。',
    'apps.menu.essential': '旅行必备APP',
    'apps.menu.hotels': '酒店预定',
    'apps.menu.transport': '交通出行',
    'apps.menu.sites': '权威网站',
    'apps.menu.youtube': 'YouTube达人',
    'apps.menu.tiktok': 'TikTok达人',
    'apps.menu.hotline': '服务热线',
    'apps.ad.label': '广告',
  },
  en: {
    'nav.home': 'Home',
    'nav.visa': 'Visa',
    'nav.discover': 'Discover',
    'nav.tools': 'Tools',
    'nav.catalog': 'Catalog',
    'nav.slogan': 'Travel China, Let’s Go',
    'nav.lang': 'English',
    'nav.lang.code': 'EN',
    'visa.mega.title': 'Visa-Free Entry to China',
    'visa.mega.desc': 'Travel to China without a visa! Learn about China\'s 240-hour transit visa-free policy, unilateral visa-free countries, and mutual visa exemption countries.',
    'visa.mega.view': 'View Now',
    'visa.types': 'Visa Types',
    'visa.photo': 'Photo Requirements',
    'visa.fee': 'Fee Standards',
    'visa.form': 'Fill Application Form',
    'visa.card': 'Arrival Card Guide',
    'discover.hotCities': 'Popular Cities',
    'discover.moreCities': 'More Cities',
    'discover.guides': 'Travel Stories',
    'discover.guides.desc': 'Practical tips from experts to help you explore China easily',
    'discover.pocket': 'China Travel Kit',
    'discover.pocket.desc': 'Master China travel in 5 mins. For beginners, a must-see for your first trip',
    'tools.menu': 'Chinese Menu Scanner',
    'tools.menu.desc': 'Upload photos to get translations, ingredients, and prices for easy ordering',
    'tools.name': 'Chinese Name Master',
    'tools.name.desc': 'AI-powered Chinese name generator for career, travel, or living in China',
    'tools.pinyin': 'Pinyin & Segmentation',
    'tools.pinyin.desc': 'Convert Chinese to Pinyin, smart segmentation, and stroke order animation',
    'tools.counter': 'Character Counter',
    'tools.counter.desc': 'Accurate stats for Chinese, English, numbers, and symbols',
    'tools.zodiac': 'Zodiac Calculator',
    'tools.zodiac.desc': 'Calculate your Chinese zodiac sign and learn its cultural meaning.',
    'footer.about': 'About Us',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.desc': 'TripCNGo provides comprehensive guides and tools for your journey to China.',
    'hero.title': 'Discover the Real China',
    'hero.subtitle': 'One-stop service from visa guides to travel tips for your China trip',
    'hero.ultimate': 'Your Ultimate Guide for Traveling to China',
    'hero.desc': 'Providing visa policies, Chinese culture, and AI tools to help you explore China with ease',
    'hero.dest': 'Destination',
    'hero.aiName': 'AI Name Master',
    'hero.searchPlaceholder': 'Enter city you want to visit',
    'hero.start': 'Search',
    'visa.section.title': 'About the 240-Hour Transit Visa-Free Policy',
    'visa.section.desc': 'China has expanded the 144-hour and newly introduced 240-hour transit visa-free policies to multiple countries. Eligible foreign travelers and business people can enter through designated ports and stay in designated areas for up to 6–10 days without prior visa application.',
    'visa.stat.countries': '54 Countries',
    'visa.stat.countries.desc': 'Open Countries',
    'visa.stat.stay': '240h',
    'visa.stat.stay.desc': 'Max Stay',
    'visa.stat.provinces': '24',
    'visa.stat.provinces.desc': 'Open Provinces',
    'visa.stat.ports': '60+',
    'visa.stat.ports.desc': 'Entry Ports',
    'home.cities.title': 'Popular Chinese Cities',
    'home.cities.more': 'More Cities',
    'home.guides.title': 'Wandering Guides',
    'home.guides.more': 'More Stories',
    'home.guides.helpful': 'people found this helpful',
    'home.faq.title': 'FAQ',
    'home.faq.subtitle': 'Questions about 144/240-hour transit visa-free policies',
    'guide.cat.all': 'All',
    'guide.cat.policy': 'National Policy',
    'guide.cat.payment': 'Payment Methods',
    'guide.cat.transport': 'Transportation',
    'guide.cat.tools': 'Practical Tools',
    'guide.cat.city': 'City Guide',
    'guide.cat.tradition': 'Tradition',
    'guide.cat.food': 'Food Culture',
    'footer.brand.title': 'tripcngo.com',
    'footer.brand.desc': 'tripcngo.com is a travel brand focused on reducing information gaps for travelers to China, enhancing the independent travel experience, and sharing Chinese culture with the world.',
    'footer.links.visa': 'Visa Info',
    'footer.links.visa.all': 'Visa-Free Guide',
    'footer.links.visa.dest': 'Discover Cities',
    'footer.links.visa.nav': 'Navigation Info',
    'footer.links.company': 'Company',
    'footer.links.about': 'About Us',
    'footer.links.terms': 'Terms of Service',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.feedback': 'Feedback',
    'feedback.title': 'Contact Us',
    'feedback.subtitle': 'Submit your suggestions for Wandering China or questions you wish to resolve, we will reply as soon as possible',
    'feedback.name': 'Name',
    'feedback.name.placeholder': 'Enter your name',
    'feedback.email': 'Email',
    'feedback.email.placeholder': 'Enter your email',
    'feedback.message': 'Message',
    'feedback.message.placeholder': 'What is the biggest problem you face in China? Or give us suggestions, we will provide feedback and help sincerely.',
    'feedback.submit': 'Submit',
    'feedback.success': 'Submitted successfully! We will reply as soon as possible.',
    'feedback.error': 'Submission failed, please try again later.',
    'footer.links.lang': 'Language',
    'footer.copy': '© 2026 tripcngo.com. All rights reserved.',
    'about.hero.title': 'Why Choose Us?',
    'about.features.team.title': 'Local Professional Team',
    'about.features.team.desc': 'We are a group of travel enthusiasts who understand the latest policies and off-the-beaten-path destinations.',
    'about.features.focus.title': 'Focus on Independent Travel',
    'about.features.focus.desc': 'We serve free spirits who prefer independent travel, providing personalized and customized solutions.',
    'about.features.ai.title': 'Smart AI Assistance',
    'about.features.ai.desc': 'Our AI assistant understands your needs, creating custom itineraries and guides for a worry-free trip.',
    'about.story.title': 'Our Story',
    'about.story.p1': 'The birth of tripcngo.com stems from our passion for China and obsession with the travel experience.',
    'about.story.p2': 'We believe travel should be spontaneous and full of surprises, not just checking in at popular spots.',
    'about.story.p3': 'With the 240-hour transit visa-free policy, more friends are visiting China. However, challenges like language, internet, and payments can be daunting.',
    'about.story.p4': 'So we created tripcngo.com to bridge the information gap, combining our travel expertise with AI technology.',
    'about.story.p5': 'From visa guides to smart helpers, we help you discover the real and beautiful China.',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'tripcngo.com was created by these exceptional individuals',
    'privacy.hero.title': 'Privacy Policy',
    'privacy.hero.subtitle': 'We are committed to protecting your personal information and privacy.',
    'privacy.lastUpdated': 'Last updated: April 26, 2025',
    'terms.hero.title': 'Terms of Service',
    'terms.hero.subtitle': 'By using our website, you agree to these terms.',
    'guide.noArticles': 'No articles found yet, we are working on it...',
    'guide.prev': 'Previous',
    'guide.next': 'Next',
    'guide.recommend': 'Recommended Guides',
    'guide.recommendCity': 'Recommended Cities',
    'guide.views': 'views',
    'guide.helpful': 'found helpful',
    'guide.updated': 'Updated',
    'guide.author': 'Author',
    'guide.inCategory': 'In ',
    'guide.readMore': 'Read More',
    'guide.backToList': 'Back to List',
    'guide.articleNotFound': 'Article Not Found',
    'guide.prevPost': 'Previous',
    'guide.nextPost': 'Next',
    'tools.name.inputLabel': 'Name or Meaning',
    'tools.name.placeholder': "e.g. Jonathan, or 'brave'",
    'tools.name.gender': 'Gender',
    'tools.name.male': 'Male',
    'tools.name.female': 'Female',
    'tools.name.button': 'Generate Name',
    'tools.name.generating': 'Generating...',
    'tools.pinyin.inputPlaceholder': 'Enter Chinese sentence to start analyzing...',
    'tools.pinyin.button': 'Analyze',
    'tools.pinyin.result': 'Analysis Result:',
    'zodiac.title': 'Chinese Zodiac Calculator',
    'apps.hero.title': 'Must-Have Apps for China 2026',
    'apps.hero.subtitle': '(v2.0)',
    'apps.hero.desc': 'Google and Uber don\'t work in China? No worries. This guide lists the 2026 essential apps favored by locals, covering mobile payments, transport, social media, and food delivery, helping you travel China like a pro.',
    'apps.menu.essential': 'Essential Apps',
    'apps.menu.hotels': 'Hotel Booking',
    'apps.menu.transport': 'Transportation',
    'apps.menu.sites': 'Official Sites',
    'apps.menu.youtube': 'YouTube Creators',
    'apps.menu.tiktok': 'TikTok Creators',
    'apps.menu.hotline': 'Service Hotlines',
    'apps.ad.label': 'Ads',
    'zodiac.subtitle': 'Check your Chinese zodiac sign by birthday, learn about its culture and travel inspiration.',
    'tools.hero.title': 'Travel Tools',
    'tools.hero.subtitle': 'Handy utilities to make your China trip easier',
    'tools.char.title': 'Character Counter',
    'tools.char.desc': 'Paste text for quick character statistics.',
    'tools.char.total': 'Total',
    'tools.char.zh': 'Chinese',
    'tools.char.en': 'English',
    'tools.char.digits': 'Digits',
    'tools.char.punc': 'Punctuation',
    'tools.char.placeholder': 'Paste or enter text to start counting...',
    'tools.zodiac.search': 'Check Your Zodiac Sign',
    'tools.menu.hero.title': 'Transform Chinese Menus into Images',
    'tools.menu.hero.desc': 'One-click menu scanning with DeepSeek V4 level precision. Get bilingual translations, visual food matches, and currency conversion.',
    'tools.menu.upload.title': 'Upload Menu Image',
    'tools.menu.upload.subtitle': 'Precise Dish Extraction & Instant Translation',
    'tools.menu.upload.button': 'Select Image',
    'tools.menu.status.reset': 'Reset & Retry',
    'tools.menu.status.analyzing': 'DeepSeek is performing deep analysis...',
    'tools.menu.label.raw': 'Raw Recognition Area',
    'tools.menu.label.refined': 'DeepSeek Optimized Results',
    'tools.menu.placeholder': 'Please upload a menu first',
    'tools.menu.feature.1.title': 'Deep Recognition',
    'tools.menu.feature.1.desc': 'AI model optimized for handwritten and artistic fonts.',
    'tools.menu.feature.2.title': 'Visual Generation',
    'tools.menu.feature.2.desc': 'See the dish visually before you order.',
    'tools.menu.feature.3.title': 'Currency Conversion',
    'tools.menu.feature.3.desc': 'Real-time FX conversion for better budgeting.',
    'tools.menu.feature.4.title': 'Voice Assistant',
    'tools.menu.feature.4.desc': 'Standard Chinese pronunciation for easy ordering.',
    'tools.zodiac.year': 'Birth Year',
    'tools.zodiac.month': 'Birth Month',
    'tools.zodiac.day': 'Birth Day',
    'tools.zodiac.button': 'Check My Zodiac Sign',
    'tools.zodiac.monthUnit': '',
    'tools.zodiac.dayUnit': '',
    'tools.zodiac.result': 'Result: Born in {year}, your zodiac sign is: ',
    'tools.zodiac.faq1.title': 'When does the zodiac year change?',
    'tools.zodiac.faq1.desc': 'The zodiac sign does not change on January 1st, but on the Chinese New Year (Lunar New Year).',
    'tools.zodiac.faq2.title': 'Twelve Zodiac Signs',
    'tools.zodiac.faq2.desc': 'There are 12 signs: Rat, Ox, Tiger, Rabbit, Dragon, Snake, Horse, Goat, Monkey, Rooster, Dog, and Pig.',
    'tools.name.title': 'Chinese Name Generator',
    'tools.pinyin.title': 'Pinyin Segmentation',
    'guide.hero.title': 'China Travel Kit',
    'guide.hero.subtitle': 'Master China travel in 5 mins. For beginners, a must-see for your first trip',
    'guide.hero.desc': 'This toolkit is designed for foreigners visiting China for the first time, aiming to solve the most urgent and common "pain points" so you can quickly understand China and start a pleasant trip.',
    'guide.toolbox.title': 'Digital Survival Kit',
    'guide.toolbox.desc': 'Essential guide for internet connection and mobile payments',
    'guide.toolbox.vpn.important': 'IMPORTANT',
    'guide.toolbox.vpn.note': 'You MUST download and install a VPN before entering China! It cannot be downloaded inside China.',
    'guide.toolbox.vpn.why': 'Why do I need a VPN?',
    'guide.toolbox.net': 'Mobile Network Options',
    'guide.toolbox.payment.status': 'China has entered a quasi-cashless society',
    'guide.toolbox.payment.manual': 'Payment Manual',
    'guide.toolbox.payment.setup': 'Setup Steps',
    'guide.toolbox.payment.alipay': 'First Pick: Alipay',
    'guide.toolbox.lang.title': 'Language Toolbox',
    'guide.toolbox.lang.desc': 'High-frequency vocabulary and daily conversations',
    'guide.toolbox.lang.core': 'Core Vocabulary',
    'guide.toolbox.lang.phrases': 'Scenario Dialogues',
    'guide.toolbox.chars.title': 'Core Characters Recognition',
    'guide.toolbox.culture.title': 'Cultural Compass',
    'guide.toolbox.discover': 'Discover More',
    'cities.hero.title': 'Popular Chinese Cities',
    'cities.hero.desc': 'Explore the most popular cities in China. Discover what\'s fun in Beijing, Shanghai, Guangzhou, and find top food and shopping recommendations.',
    'cities.intro.title': 'Intro to China',
    'cities.intro.p1': 'The People\'s Republic of China is one of the oldest countries in the world, with 5,000 years of civilization.',
    'cities.intro.p2': 'Located in East Asia, China was founded in 1949. It is one of the world\'s most populous countries with 1.4 billion people and an area of 9.6 million sq km (3rd largest).',
    'cities.intro.p3': 'The terrain follows a three-step ladder from the high Qinghai-Tibet Plateau in the west to the low plains and coastline in the east. This fall creates diverse landscapes including deserts, plateaus, and basins.',
    'cities.intro.p4': 'China is divided into 23 provinces, 5 autonomous regions, 4 municipalities (Beijing, Shanghai, Tianjin, Chongqing), and 2 SARs (Hong Kong, Macau).',
    'cities.intro.p5': 'Unified multi-ethnic country with 56 ethnic groups. Han is the majority. Mandarin is the common language.',
    'cities.intro.p6': 'Chinese culture is profound and colorful. It holds a significant position in world culture. Traditional arts include poetry, opera, calligraphy, and painting.',
    'city.beijing': 'Beijing',
    'city.shanghai': 'Shanghai',
    'city.guangzhou': 'Guangzhou',
    'city.shenzhen': 'Shenzhen',
    'city.hangzhou': 'Hangzhou',
    'city.chongqing': 'Chongqing',
    'city.chengdu': 'Chengdu',
    'city.xian': 'Xi\'an',
    'city.changsha': 'Changsha',
    'city.xiamen': 'Xiamen',
    'footer.links.partners': 'Partners',
    'city.tags.visaFree': '240h Visa-Free',
    'city.stats.wantToVisit': 'Want to Visit',
    'city.stats.recommended': 'Recommended',
    'city.weather.timeTitle': 'Time',
    'city.weather.area': 'Area',
    'city.weather.population': 'Population',
    'city.bestTime.title': 'Best Travel Time',
    'city.bestTime.descPrefix': 'The best time to visit ',
    'city.bestTime.descSuffix': ' is ',
    'city.history.title': 'History & Culture',
    'city.attractions.title': 'Attractions',
    'city.attractions.subtitle': 'Recommended places to visit',
    'city.attractions.ticket': 'Ticket',
    'city.attractions.season': 'Best Season',
    'city.attractions.time': 'Recommended Time',
    'city.heritage.world.title': 'World Heritage',
    'city.heritage.world.subtitle': 'UNESCO World Heritage Sites',
    'city.heritage.intangible.title': 'Intangible Heritage',
    'city.heritage.intangible.subtitle': 'Explore rich intangible cultural heritage and traditional crafts',
    'city.transport.title': 'Transportation',
    'city.transport.subtitle': 'Must-know transportation for exploring the city',
    'city.food.title': 'Food & Snacks',
    'city.food.subtitle': 'Taste the most authentic and popular local specialties',
    'city.food.ingredients': 'Ingredients',
    'city.explore.title': 'Explore Deeper',
    'city.explore.travel': 'Travel Tips',
    'city.explore.hotels': 'Hotels & Accommodation',
    'city.explore.tools': 'Internet Usage & Online Tools',
    'visa.hero.title': 'China',
    'visa.hero.legendTitle': '240h Transit Visa-Free Cities',
    'visa.hero.legendFull': 'Whole Prov/City Open',
    'visa.hero.legendPartial': 'Partial Areas Open',
    'visa.menu.types': 'Visa Types',
    'visa.menu.photo': 'Photo Req',
    'visa.menu.fee': 'Fee Standards',
    'visa.menu.form': 'Application Form',
    'visa.menu.entryCard': 'Entry Card Guide',
    'visa.menu.download': 'Downloads',
    'visa.transit.title': '240-Hour Transit Visa-Free',
    'visa.transit.countriesTitle': 'Eligible Countries (54):',
    'visa.transit.europe': 'Europe (44 countries):',
    'visa.transit.americas': 'Americas (6 countries):',
    'visa.transit.oceania': 'Oceania (2 countries):',
    'visa.transit.asia': 'Asia (6 countries):',
    'visa.transit.portsTitle': 'Applicable Ports:',
    'visa.transit.tableCity': 'City',
    'visa.transit.tablePort': 'Entry Port Name',
    'visa.transit.tableArea': 'Stay/Travel Area',
    'visa.unilateral.title': 'List of Countries with Unilateral Visa-Free Entry',
    'visa.unilateral.desc': 'Citizens of the following countries holding ordinary passports can enter China without a visa for tourism, business, and visiting relatives.',
    'visa.unilateral.tableCountry': 'Country',
    'visa.unilateral.tableDays': 'Duration',
    'visa.mutual.title': 'List of Countries with Mutual Visa-Free Agreements',
    'visa.mutual.desc': 'Citizens of both countries holding ordinary passports can usually travel to each other\'s country for short term without prior visa application.',
    'visa.mutual.tableCountry': 'Country',
    'visa.mutual.tableDays': 'Duration',
    'visa.faq.title': 'FAQ',
    'visa.sidebar.notice': 'Important Notices',
    'visa.sidebar.portTitle': 'Port Choice: 60 Designated Entry Points',
    'visa.sidebar.portDesc1': 'Eligible: Citizens of 54 countries (e.g., US, UK, Japan)',
    'visa.sidebar.portDesc2': 'Requirement: Only available at 60 designated ports like Beijing, Shanghai, Guangzhou.',
    'visa.sidebar.materialTitle': 'Preparation: Connecting Ticket + Valid Passport',
    'visa.sidebar.materialDesc1': 'Required: Passport validity > 3 months',
    'visa.sidebar.materialDesc2': 'Confirmed connecting ticket (flying to a third country within 240h, cannot return to origin)',
    'visa.sidebar.materialDesc3': 'Process: Submit documents at border inspection on arrival; entry granted after approval.',
    'visa.sidebar.areaTitle': 'Stay Area: 24 Provinces Range',
    'visa.sidebar.areaDesc1': 'Allowed: Travel or activities within 24 provinces/municipalities including Beijing, Shanghai, Sichuan.',
    'visa.sidebar.areaDesc2': 'Prohibited: Staying outside the prescribed area.',
    'visa.sidebar.ruleTitle': 'Compliance: Strict Adherence to Time & Registration',
    'visa.sidebar.ruleDesc1': 'Time: Max stay 240h (starting from 00:00 the day after entry)',
    'visa.sidebar.ruleDesc2': 'Overstay: Must apply for residence permit in advance (only for emergencies/force majeure).',
    'visa.sidebar.ruleDesc3': 'Registration: Register accommodation within 24h (hotel or police station).',
    'visa.sidebar.ruleDesc4': 'Restricted: Only for short-term tourism/business; prohibited from working/studying.',
    'visa.sidebar.disclaimer': 'Disclaimer: Information provided is for reference only. For specific policies, please refer to the official NIA website. Policies subject to change.',
    'visa.sidebar.niaTitle': 'National Immigration Administration',
    'visa.sidebar.hotline': 'Service Hotline',
    'visa.sidebar.interaction': 'Interaction',
    'visa.sidebar.ask': 'Click to Ask',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('tripcngo_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('tripcngo_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
