import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Simplified translation helper for common UI elements
const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.home': '首页',
    'nav.visa': '签证',
    'nav.discover': '发现',
    'nav.tools': '工具',
    'nav.catalog': '目录',
    'nav.lang': '简体中文',
    'nav.lang.code': 'CN',
    'visa.mega.title': '来华免签大全',
    'visa.mega.desc': '无需签证，畅游中国！全面了解中国240小时过境免签政策和国家，中国单方面免签国家，中外互免签证国家，开启您的精彩中国之旅！',
    'visa.mega.view': '立即查看',
    'visa.types': '签证类型',
    'visa.photo': '照片要求',
    'visa.fee': '费用标准',
    'visa.form': '填写申请表',
    'visa.card': '入境卡填写指南',
    'discover.hotCities': '热门城市',
    'discover.moreCities': '更多城市',
    'discover.guides': '经验攻略',
    'discover.guides.desc': '资深达人分享实用攻略，助你轻松玩转中国',
    'discover.pocket': '中国旅行锦囊',
    'discover.pocket.desc': '5分钟掌握入华锦囊，针对来华新手打造，第一次去中国必看',
    'tools.menu': '中文菜单转图神器',
    'tools.menu.desc': '上传照片，可获得图片、翻译、食材和价格，助您轻松点餐',
    'tools.name': '中文名取名大师',
    'tools.name.desc': '使用AI推理模型中文名，适合在中国职业发展、交友、旅游或生活',
    'tools.pinyin': '中文转拼音和分词',
    'tools.pinyin.desc': '可将任何中文句子转换为标准拼音、智能分词，查看每个字的笔顺动画',
    'tools.counter': '中文字符计数器',
    'tools.counter.desc': '精确统计汉字、英文、数字、标点、行数与总字符数',
    'tools.zodiac': '中国生肖计算器',
    'tools.zodiac.desc': '根据生日计算中国生肖，查看本命年时间，并了解每个生肖的文化含义。',
    'footer.about': '关于我们',
    'footer.contact': '联系我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.desc': 'TripCNGo 为您的中国之旅提供全面指南和实用工具。',
    'hero.title': '发现真实的中国',
    'hero.subtitle': '从签证指南到旅行锦囊，我们为您提供一站式入华服务',
    'hero.ultimate': '您中国旅行的终极指南',
    'hero.desc': '提供免签政策、中国文化、AI智能工具，助您轻松探索中国',
    'hero.dest': '目的地',
    'hero.aiName': 'AI中英文取名大师',
    'hero.searchPlaceholder': '请输入您想去的城市',
    'hero.start': '开始',
    'visa.section.title': '关于240小时过境免签政策',
    'visa.section.desc': '中国扩大了对多个国家的144小时及最新推出的240小时过境免签政策。符合条件的外国旅游者、商务人士可以通过指定口岸入境，无需事先申请签证即可在中国指定区域内停留最长不超过6天至10天。',
    'visa.stat.countries': '54国',
    'visa.stat.countries.desc': '开放国家',
    'visa.stat.stay': '240h',
    'visa.stat.stay.desc': '停留时长',
    'visa.stat.provinces': '24个',
    'visa.stat.provinces.desc': '开放省份',
    'visa.stat.ports': '60+',
    'visa.stat.ports.desc': '入境口岸',
    'home.cities.title': '热门中国城市',
    'home.cities.more': '更多城市',
    'home.guides.title': '漫游指南',
    'home.guides.more': '更多攻略',
    'home.guides.helpful': '人认为有用',
    'home.faq.title': '常见问题',
    'home.faq.subtitle': '关于144/240小时过境免签政策问答',
    'footer.brand.title': '漫游中国指南',
    'footer.brand.desc': 'tripcngo.com，是一个专注于减少中国旅游信息差，提升入境自由行旅游体验的旅游品牌，致力于向世界传播中国文化，发现真实美好的中国；',
    'footer.links.visa': '入境签证',
    'footer.links.visa.all': '来华免签大全',
    'footer.links.visa.dest': '发现目的地',
    'footer.links.visa.nav': '导航信息',
    'footer.links.company': '公司',
    'footer.links.about': '关于我们',
    'footer.links.terms': '服务条款',
    'footer.links.privacy': '隐私政策',
    'footer.links.feedback': '意见反馈',
    'footer.links.lang': '语言',
    'footer.links.partners': '合作伙伴',
    'city.tags.visaFree': '240小时过境免签',
    'city.stats.wantToVisit': '想去',
    'city.stats.recommended': '推荐',
    'city.weather.timeTitle': '时间',
    'city.weather.area': '面积',
    'city.weather.population': '常住人口',
    'city.bestTime.title': '最佳旅行时间',
    'city.bestTime.descPrefix': '游览',
    'city.bestTime.descSuffix': '的最佳时间是',
    'city.history.title': '历史与文化',
    'city.attractions.title': '景点',
    'city.attractions.subtitle': '有哪些好玩的推荐',
    'city.attractions.ticket': '门票',
    'city.attractions.season': '适宜季节',
    'city.attractions.time': '建议游玩',
    'city.heritage.world.title': '世界遗产名录',
    'city.heritage.world.subtitle': '拥有的联合国教科文组织世界遗产',
    'city.heritage.intangible.title': '非物质文化遗产',
    'city.heritage.intangible.subtitle': '探索丰富的非物质文化遗产，了解传统工艺与文化精髓',
    'city.transport.title': '交通指南',
    'city.transport.subtitle': '你必须知道的交通工具',
    'city.food.title': '美食',
    'city.food.subtitle': '品尝最地道、最受欢迎的特色美食与小吃',
    'city.food.ingredients': '主要食材',
    'city.explore.title': '深入探索',
    'city.explore.travel': '旅行',
    'city.explore.hotels': '酒店与住宿',
    'city.explore.tools': '网络如何用与在线工具',
    'visa.hero.title': '中国',
    'visa.hero.legendTitle': '240小时过境免签开放城市',
    'visa.hero.legendFull': '全省/市开放',
    'visa.hero.legendPartial': '部分地区开放',
    'visa.menu.types': '签证类型',
    'visa.menu.photo': '照片要求',
    'visa.menu.fee': '费用标准',
    'visa.menu.form': '填写申请表',
    'visa.menu.entryCard': '入境卡填写指南',
    'visa.menu.download': '材料下载',
    'visa.transit.title': '来华240小时过境免签',
    'visa.transit.countriesTitle': '开放国家 (54个)：',
    'visa.transit.europe': '欧洲 (44个国家)：',
    'visa.transit.americas': '美洲 (6个国家)：',
    'visa.transit.oceania': '大洋洲 (2个国家)：',
    'visa.transit.asia': '亚洲 (6个国家)：',
    'visa.transit.portsTitle': '适用口岸：',
    'visa.transit.tableCity': '城市',
    'visa.transit.tablePort': '入境口岸名称',
    'visa.transit.tableArea': '停留活动范围',
    'visa.unilateral.title': '单方面免签国家一览表',
    'visa.unilateral.desc': '中国向以下国家持普通护照公民来华旅游、经商、探亲等开放免签，入境无需提前申请签证',
    'visa.unilateral.tableCountry': '国家名称',
    'visa.unilateral.tableDays': '停留天数',
    'visa.mutual.title': '互免签证协定国家一览表',
    'visa.mutual.desc': '双方国家公民持因私普通护照来往，彼此国家短期旅行通常无需事先申请签证',
    'visa.mutual.tableCountry': '国家名称',
    'visa.mutual.tableDays': '停留天数',
    'visa.faq.title': '常见问题',
    'visa.sidebar.notice': '注意事项',
    'visa.sidebar.portTitle': '选口岸：60个指定入境点',
    'visa.sidebar.portDesc1': '适用人群：54国公民（如美、英、日等）',
    'visa.sidebar.portDesc2': '入境要求：仅限北京、上海、广州等60个指定口岸，其他口岸不可用。',
    'visa.sidebar.materialTitle': '备材料：联程机票+有效护照',
    'visa.sidebar.materialDesc1': '必备文件：护照有效期 > 3个月',
    'visa.sidebar.materialDesc2': '已订妥的联程机票（入境后240小时内飞往第三国，不可返回出发国）',
    'visa.sidebar.materialDesc3': '申请流程：入境时向口岸边检提交材料，审核通过后放行。',
    'visa.sidebar.areaTitle': '守区域：24省活动范围',
    'visa.sidebar.areaDesc1': '允许范围：可在北京、上海、四川等24个省（区、市）内旅游或跨省活动。',
    'visa.sidebar.areaDesc2': '禁止行为：超出规定区域停留。',
    'visa.sidebar.ruleTitle': '遵法规：时限与登记严遵守',
    'visa.sidebar.ruleDesc1': '时限要求：最长停留240小时（从入境次日0时起算）',
    'visa.sidebar.ruleDesc2': '超时/超范围：须提前向公安机关申请停留证件（仅限紧急或不可抗力）。',
    'visa.sidebar.ruleDesc3': '登记义务：入境24小时内办理住宿登记（酒店或派出所）。',
    'visa.sidebar.ruleDesc4': '仅限旅游、商务等短期活动，禁止工作或学习。',
    'visa.sidebar.disclaimer': '免责声明：本网站提供的信息仅供参考，具体政策请以中国国家移民管理局官方发布为准。政策可能随时调整，请在出行前确认最新规定。',
    'visa.sidebar.niaTitle': '中国移民管理局',
    'visa.sidebar.hotline': '服务热线',
    'visa.sidebar.interaction': '互动交流',
    'visa.sidebar.ask': '点击提问',
  },
  en: {
    'nav.home': 'Home',
    'nav.visa': 'Visa',
    'nav.discover': 'Discover',
    'nav.tools': 'Tools',
    'nav.catalog': 'Catalog',
    'nav.lang': 'English',
    'nav.lang.code': 'EN',
    'visa.mega.title': 'Visa-Free Entry to China',
    'visa.mega.desc': 'Travel to China without a visa! Learn about China\'s 240-hour transit visa-free policy, unilateral visa-free countries, and mutual visa exemption countries.',
    'visa.mega.view': 'View Now',
    'visa.types': 'Visa Types',
    'visa.photo': 'Photo Requirements',
    'visa.fee': 'Fee Standards',
    'visa.form': 'Fill Application Form',
    'visa.card': 'Arrival Card Guide',
    'discover.hotCities': 'Popular Cities',
    'discover.moreCities': 'More Cities',
    'discover.guides': 'Travel Stories',
    'discover.guides.desc': 'Practical tips from experts to help you explore China easily',
    'discover.pocket': 'China Travel Kit',
    'discover.pocket.desc': 'Master China travel in 5 mins. For beginners, a must-see for your first trip',
    'tools.menu': 'Chinese Menu Scanner',
    'tools.menu.desc': 'Upload photos to get translations, ingredients, and prices for easy ordering',
    'tools.name': 'Chinese Name Master',
    'tools.name.desc': 'AI-powered Chinese name generator for career, travel, or living in China',
    'tools.pinyin': 'Pinyin & Segmentation',
    'tools.pinyin.desc': 'Convert Chinese to Pinyin, smart segmentation, and stroke order animation',
    'tools.counter': 'Character Counter',
    'tools.counter.desc': 'Accurate stats for Chinese, English, numbers, and symbols',
    'tools.zodiac': 'Zodiac Calculator',
    'tools.zodiac.desc': 'Calculate your Chinese zodiac sign and learn its cultural meaning.',
    'footer.about': 'About Us',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.desc': 'TripCNGo provides comprehensive guides and tools for your journey to China.',
    'hero.title': 'Discover the Real China',
    'hero.subtitle': 'One-stop service from visa guides to travel tips for your China trip',
    'hero.ultimate': 'Your Ultimate Guide for Traveling to China',
    'hero.desc': 'Providing visa policies, Chinese culture, and AI tools to help you explore China with ease',
    'hero.dest': 'Destination',
    'hero.aiName': 'AI Name Master',
    'hero.searchPlaceholder': 'Enter city you want to visit',
    'hero.start': 'Search',
    'visa.section.title': 'About the 240-Hour Transit Visa-Free Policy',
    'visa.section.desc': 'China has expanded the 144-hour and newly introduced 240-hour transit visa-free policies to multiple countries. Eligible foreign travelers and business people can enter through designated ports and stay in designated areas for up to 6–10 days without prior visa application.',
    'visa.stat.countries': '54 Countries',
    'visa.stat.countries.desc': 'Open Countries',
    'visa.stat.stay': '240h',
    'visa.stat.stay.desc': 'Max Stay',
    'visa.stat.provinces': '24',
    'visa.stat.provinces.desc': 'Open Provinces',
    'visa.stat.ports': '60+',
    'visa.stat.ports.desc': 'Entry Ports',
    'home.cities.title': 'Popular Chinese Cities',
    'home.cities.more': 'More Cities',
    'home.guides.title': 'Wandering Guides',
    'home.guides.more': 'More Stories',
    'home.guides.helpful': 'people found this helpful',
    'home.faq.title': 'FAQ',
    'home.faq.subtitle': 'Questions about 144/240-hour transit visa-free policies',
    'footer.brand.title': 'Wandering China Guide',
    'footer.brand.desc': 'tripcngo.com is a travel brand focused on reducing information gaps for travelers to China, enhancing the independent travel experience, and sharing Chinese culture with the world.',
    'footer.links.visa': 'Visa Info',
    'footer.links.visa.all': 'Visa-Free Guide',
    'footer.links.visa.dest': 'Discover Cities',
    'footer.links.visa.nav': 'Navigation Info',
    'footer.links.company': 'Company',
    'footer.links.about': 'About Us',
    'footer.links.terms': 'Terms of Service',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.feedback': 'Feedback',
    'footer.links.lang': 'Language',
    'footer.links.partners': 'Partners',
    'city.tags.visaFree': '240h Visa-Free',
    'city.stats.wantToVisit': 'Want to Visit',
    'city.stats.recommended': 'Recommended',
    'city.weather.timeTitle': 'Time',
    'city.weather.area': 'Area',
    'city.weather.population': 'Population',
    'city.bestTime.title': 'Best Travel Time',
    'city.bestTime.descPrefix': 'The best time to visit ',
    'city.bestTime.descSuffix': ' is ',
    'city.history.title': 'History & Culture',
    'city.attractions.title': 'Attractions',
    'city.attractions.subtitle': 'Recommended places to visit',
    'city.attractions.ticket': 'Ticket',
    'city.attractions.season': 'Best Season',
    'city.attractions.time': 'Recommended Time',
    'city.heritage.world.title': 'World Heritage',
    'city.heritage.world.subtitle': 'UNESCO World Heritage Sites',
    'city.heritage.intangible.title': 'Intangible Heritage',
    'city.heritage.intangible.subtitle': 'Explore rich intangible cultural heritage and traditional crafts',
    'city.transport.title': 'Transportation',
    'city.transport.subtitle': 'Must-know transportation for exploring the city',
    'city.food.title': 'Food & Snacks',
    'city.food.subtitle': 'Taste the most authentic and popular local specialties',
    'city.food.ingredients': 'Ingredients',
    'city.explore.title': 'Explore Deeper',
    'city.explore.travel': 'Travel Tips',
    'city.explore.hotels': 'Hotels & Accommodation',
    'city.explore.tools': 'Internet Usage & Online Tools',
    'visa.hero.title': 'China',
    'visa.hero.legendTitle': '240h Transit Visa-Free Cities',
    'visa.hero.legendFull': 'Whole Prov/City Open',
    'visa.hero.legendPartial': 'Partial Areas Open',
    'visa.menu.types': 'Visa Types',
    'visa.menu.photo': 'Photo Req',
    'visa.menu.fee': 'Fee Standards',
    'visa.menu.form': 'Application Form',
    'visa.menu.entryCard': 'Entry Card Guide',
    'visa.menu.download': 'Downloads',
    'visa.transit.title': '240-Hour Transit Visa-Free',
    'visa.transit.countriesTitle': 'Eligible Countries (54):',
    'visa.transit.europe': 'Europe (44 countries):',
    'visa.transit.americas': 'Americas (6 countries):',
    'visa.transit.oceania': 'Oceania (2 countries):',
    'visa.transit.asia': 'Asia (6 countries):',
    'visa.transit.portsTitle': 'Applicable Ports:',
    'visa.transit.tableCity': 'City',
    'visa.transit.tablePort': 'Entry Port Name',
    'visa.transit.tableArea': 'Stay/Travel Area',
    'visa.unilateral.title': 'List of Countries with Unilateral Visa-Free Entry',
    'visa.unilateral.desc': 'Citizens of the following countries holding ordinary passports can enter China without a visa for tourism, business, and visiting relatives.',
    'visa.unilateral.tableCountry': 'Country',
    'visa.unilateral.tableDays': 'Duration',
    'visa.mutual.title': 'List of Countries with Mutual Visa-Free Agreements',
    'visa.mutual.desc': 'Citizens of both countries holding ordinary passports can usually travel to each other\'s country for short term without prior visa application.',
    'visa.mutual.tableCountry': 'Country',
    'visa.mutual.tableDays': 'Duration',
    'visa.faq.title': 'FAQ',
    'visa.sidebar.notice': 'Important Notices',
    'visa.sidebar.portTitle': 'Port Choice: 60 Designated Entry Points',
    'visa.sidebar.portDesc1': 'Eligible: Citizens of 54 countries (e.g., US, UK, Japan)',
    'visa.sidebar.portDesc2': 'Requirement: Only available at 60 designated ports like Beijing, Shanghai, Guangzhou.',
    'visa.sidebar.materialTitle': 'Preparation: Connecting Ticket + Valid Passport',
    'visa.sidebar.materialDesc1': 'Required: Passport validity > 3 months',
    'visa.sidebar.materialDesc2': 'Confirmed connecting ticket (flying to a third country within 240h, cannot return to origin)',
    'visa.sidebar.materialDesc3': 'Process: Submit documents at border inspection on arrival; entry granted after approval.',
    'visa.sidebar.areaTitle': 'Stay Area: 24 Provinces Range',
    'visa.sidebar.areaDesc1': 'Allowed: Travel or activities within 24 provinces/municipalities including Beijing, Shanghai, Sichuan.',
    'visa.sidebar.areaDesc2': 'Prohibited: Staying outside the prescribed area.',
    'visa.sidebar.ruleTitle': 'Compliance: Strict Adherence to Time & Registration',
    'visa.sidebar.ruleDesc1': 'Time: Max stay 240h (starting from 00:00 the day after entry)',
    'visa.sidebar.ruleDesc2': 'Overstay: Must apply for residence permit in advance (only for emergencies/force majeure).',
    'visa.sidebar.ruleDesc3': 'Registration: Register accommodation within 24h (hotel or police station).',
    'visa.sidebar.ruleDesc4': 'Restricted: Only for short-term tourism/business; prohibited from working/studying.',
    'visa.sidebar.disclaimer': 'Disclaimer: Information provided is for reference only. For specific policies, please refer to the official NIA website. Policies subject to change.',
    'visa.sidebar.niaTitle': 'National Immigration Administration',
    'visa.sidebar.hotline': 'Service Hotline',
    'visa.sidebar.interaction': 'Interaction',
    'visa.sidebar.ask': 'Click to Ask',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
